spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/sport_hub?serverTimezone=UTC
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=qwe.123!
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
security.jwt.expiration-time=3600000
security.jwt.refresh-expiration-time=604800000
security.jwt.reset-expiration-time=600000
security.jwt.activation-expiration-time=600000
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=/tmp/uploads
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

strava.client.base-url=https://www.strava.com/api/v3
strava.client.client-id=149396
strava.client.secret=0d058f0a7fb09db4d7697c07ea9f842f6f625dd4
strava.client.redirect-uri=http://localhost:5173/connectStrava
strava.client.scopes=read,activity:read_all,activity:write
strava.client.webhook-verify-token=bhf7s92dkfX1zq3m
strava.client.jasypt-encryptor-password=mySuperSecretPassword123

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pierpacas01@gmail.com
spring.mail.password=qhok pcax zhsp mquo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=no-reply@sporthub.com

telegram.base-url=https://api.telegram.org
telegram.bot-token=7387350060:AAENNcBr4zHFtwoRAEFSKX7RYoIHGypj0Mw
telegram.bot-username =sporthub_val_pier_bot
telegram.bot-url-link=https://t.me/

server.error.whitelabel.enabled=false
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-exception=true
server.error.include-stacktrace=never
